# Reverse proxy server

services:
  proxy_server:
    image: docker.io/jc21/nginx-proxy-manager:latest
    container_name: proxy_server
    restart: unless-stopped
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      - docker_proxy01
    ports:
      - "80:80"
      - "443:443"
      - "8081:81"

volumes:
  data:
  letsencrypt:

networks:
  docker_proxy01:
    external: true
