# Reverse proxy server

services:
  proxy_server:
    image: docker.io/nginx
    container_name: proxy_server
    volumes:
      - ./templates:/etc/nginx/templates:ro
      - ./logs:/var/logs/nginx
    networks:
      - docker_proxy01
    ports:
      - "80:80"
      - "443:443"
    env_file: .env

networks:
  docker_proxy01:
    external: true
